# Generated by Django 6.1.1 on 2026-09-07 21:23

import django.core.validators
from django.db import migrations, models


def normalize_duplicate_codes(apps, schema_editor):
    curso_model = apps.get_model('escola', 'Curso')
    used_codes = set()

    for curso in curso_model.objects.order_by('codigo', 'id'):
        if curso.codigo not in used_codes:
            used_codes.add(curso.codigo)
            continue

        suffix = 2
        base_code = curso.codigo[:8]
        new_code = f'{base_code}-{suffix}'
        while new_code in used_codes:
            suffix += 1
            new_code = f'{base_code[:7]}-{suffix}'

        curso.codigo = new_code
        curso.save(update_fields=['codigo'])
        used_codes.add(new_code)


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_estudante_cpf'),
    ]

    operations = [
        migrations.RunPython(normalize_duplicate_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
